### ISSUE TITLE
Problems with the size of the input file name

### ISSUE THREAD

**Issue by aguus8** [Discngine/fpocket#130]
Hello, 

I'm having problems with the length size of the input file's name. When it is longer than many characters (I can't say the exact amount), this error appears: 

**"malloc(): corrupted top size"**

currently, I solve this error by giving as input the relative path instead the absolute path (which is shorter). 
The version of fpocket that I'm using is: 3.1.4.2

Thanks in advance

Agustín

**Comment by pschmidtke** [comment]
fixed in 4.1.3

**Comment by aguus8** [comment]
thank u very much!

**Comment by dgozgulbas** [comment]
Hello,

I am getting the same "malloc(): corrupted top size" error due to input directory length for mdpocket while using the latest fpocket version 4.2. Can you help me with this?

Thank you,
Defne

**Comment by Dan-Burns** [comment]
I just copied the inputs to a new working directory and gave them short names. That got me past the malloc() error.. Now I'm getting a segmentation fault.

**Comment by aguus8** [comment]
I'm still having the same error "malloc(): corrupted top size" with the input length path in 4.2 version. 

Thank you, 

Agus
